### ISSUE TITLE
docker-compose.yml ?

### ISSUE THREAD

**Issue by 1000i100** [VideoCurio/ProtonMailBridgeDocker#7]
Hi, i use docker-compose to simplify my docker setup.
Why is there none on this project. Is it because you don't use it usually or for a specific reason ?

**Comment by VideoCurio** [comment]
Hi, I am not using docker compose on my machines, the plugin is not even installed. I usually use the run command or kubernetes.

If you have a working compose file, feel free to submit a patch in the testing branch and I will add it.

**Comment by VideoCurio** [comment]
Added a working compose.yaml file in today commit.
